package server.localization;

public enum StringId {
    USER_NOT_EXIST,
    USER_ALREADY_EXIST,
    USER_BAD_LOGIN,
    USER_PASSWORD_TOO_SHORT,
    USER_WRONG_CREDENTIALS,

    CONFERENCE_NOT_EXIST,
    CONFERENCE_NOT_FINISHED,
    CONFERENCE_PARTICIPANT_NOT_EXIST,

    SPEECHPAD_NOT_EXIST,

    TRANSCRIBE_UPLOAD_FAILED,
    TRANSCRIBE_NO_FILE_SENT,

    CONFERENCE_FINISH_NOT_PERMITTED,
    GENERIC_ERROR,
}
